In [1]:
import bokeh
import pandas as pd
import numpy as np
bokeh.__version__

'1.4.0'

# Dataprep

In [3]:
df_confirmed = pd.read_csv('data/time_series_covid19_confirmed_global.csv')
df_death = pd.read_csv('data/time_series_covid19_deaths_global.csv')
df_recovered = pd.read_csv('data/time_series_covid19_recovered_global.csv')

In [4]:
regions_death = df_death['Country/Region']
regions_confirmed = df_confirmed['Country/Region']
regions_recovered = df_recovered['Country/Region']

In [5]:
df_death = df_death.drop(['Province/State','Lat','Long','Country/Region'],axis=1).T
df_death.columns = regions_death
df_death.to_csv('data/death.csv')

In [6]:
df_confirmed = df_confirmed.drop(['Province/State','Lat','Long','Country/Region'],axis=1).T
df_confirmed.columns = regions_confirmed
df_confirmed.to_csv('data/confirmed.csv')

In [7]:
df_recovered= df_recovered.drop(['Province/State','Lat','Long','Country/Region'],axis=1).T
df_recovered.columns = regions_recovered
df_recovered.to_csv('data/recovered.csv')

In [10]:
regions_recovered

0                Afghanistan
1                    Albania
2                    Algeria
3                    Andorra
4                     Angola
               ...
245                   France
246              South Sudan
247           Western Sahara
248    Sao Tome and Principe
249                    Yemen
Name: Country/Region, Length: 250, dtype: object

# Load data

In [32]:
df_confirmed = pd.read_csv('data/confirmed.csv',parse_dates=[0])
df_death = pd.read_csv('data/death.csv',parse_dates=[0])
df_recovered = pd.read_csv('data/recovered.csv',parse_dates=[0])

In [33]:
df_confirmed.rename( columns={'Unnamed: 0':'date'}, inplace=True )
df_death.rename( columns={'Unnamed: 0':'date'}, inplace=True )
df_recovered.rename( columns={'Unnamed: 0':'date'}, inplace=True )

In [34]:
df_confirmed

,date,Afghanistan,Albania,Algeria,Andorra,Angola,Antigua and Barbuda,Argentina,Armenia,Australia,...,Burundi,Sierra Leone,Netherlands.4,Malawi,United Kingdom.10,France.10,South Sudan,Western Sahara,Sao Tome and Principe,Yemen
0,2020-01-22,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,2020-01-23,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,2020-01-24,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,2020-01-25,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,2020-01-26,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
87,2020-04-18,933,548,2534,704,24,23,2758,1248,103,...,5,30,3,17,11,1,4,6,4,1
88,2020-04-19,996,562,2629,713,24,23,2839,1291,103,...,5,35,5,17,11,1,4,6,4,1
89,2020-04-20,1026,584,2718,717,24,23,2941,1339,103,...,5,43,5,17,11,1,4,6,4,1
90,2020-04-21,1092,609,2811,717,24,23,3031,1401,103,...,5,50,5,18,11,1,4,6,4,1
91,2020-04-22,1176,634,2910,723,25,24,3144,1473,103,...,11,61,5,23,11,1,4,6,4,1

# Bokeh time

In [35]:
from bokeh.io import curdoc
from bokeh.layouts import column, row
from bokeh.plotting import figure, output_file, show
from bokeh.models import ColumnDataSource, PreText, Select

In [42]:
source = ColumnDataSource(df_confirmed.sample(50))
plt = figure(x_axis_type='datetime')
plt.circle(x='date', y='Afghanistan', source=source,size=10, color='green')

GlyphRenderer(id='1804', ...)

In [43]:
show(plt)